# -*- coding: utf-8 -*-
"""meu primeiro algoritmo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xx7jfTdedwXnT1pLkcEsRnYNFC06-A8x

# Documentação
## Subtitulo
"""

print('Olá, mundo.')

"""#Operadores Aritmeticos"""

#Adição
10+2

#Subtração
10-2

#Multiplicação
10*2

#Divisão
10/2

#Divisão inteira
10//2

#Resto da Divisão
10%2

#Potenciação
10**2

"""#Operadores Relacionais

"""

#Menor
10<2

#Menor ou Igual
10<=2

#Maior
10>2

#Maior ou Igual
10>=2

#Igual
10==2

#Diferente
10!=2

"""#Operadores Logicos

*   and
*   or
*   not

##Tabela verdade

and
"""

print(10 < 2 and 4 > 6)
print(10 < 2 and 4 < 6)
print(10 > 2 and 4 > 6)
print(10 > 2 and 4 < 6)

"""or"""

#or
print(10 < 2 or 4 > 6)
print(10 < 2 or 4 < 6)
print(10 > 2 or 4 > 6)
print(10 > 2 or 4 < 6)

"""not"""

not 10 < 2

not 10 > 2

"""#Variáveis

Variáveis estão alocadas em espaços na memória
"""

# Nome da variavel é "x" que armazena o valor 10 em um espaço na memória
x = 10

print(x)

"""#Visualização de Variaveis e textos"""

print('Conheça o comando print')

x = 8
print(x)

y = 10
soma = x + y
print(soma)

nome = 'Bruno Dubal'
print(nome)

"""Concatenação

"""

x = 5
print('O valor de x é', x)

print('Ovalor de x é', x, 'e o dobro é', x*2)

print('Eu,', nome, 'tirei', x, 'na prova de python')

y = 10; z = 20 + x - y
print('Declarar varias variaveis na mesma linha', y, x)

"""Type

"""

x = 10
type(x)
print('x', type(x))

nome = 'Rodrigo'
print('nome', type(nome))

num = '100'
num_convert = int(num) #converte variavel
print('num', type(num))
print('num_convert', type(num_convert))

num_float = float(num)
print('num_float', type(num_float))

"""Input
* Amazenar a informação digitada pelo usuario em uma variavel
* O dado armazenado sempre sera o um texto
"""

nome = input('Digite o nome de usuario: ') # Aguarda o usuario digitar algo
print(nome)

valor = input('Digite a nota:')

print(nome, 'sua nota foi', valor)

valor = input('Digite o valor de um produto: ')
print(valor)

desconto  = valor - 5

valor_convert = int(valor)
desconto = valor_convert - 5
print(desconto)

desconto = int(valor) - 5
print(desconto)

"""#Condicional

if
"""

if 5 < 10:
  print('verdade')

"""if/else"""

num1 = 10
num2 = 5
if num1 > num2:
  print(f'O {num1} é maior que o {num2}')
else:
  pritn(f'O {num1} é menor que o {num2}')

"""if/elif/else"""

num1 = 10
num2 = 5
if num1 > num2:
  print(f'O {num1} é maior que o {num2}')
elif num1 < num2:
  print(f'o {num2} é maior que o {num1}')
else:
  print('Os numeros sao iguais')

"""#Condicional com operadores logicos"""

num1 = 10
num2 = 5
num3 = 2
if (num1 > num2) and (num1 > num3):
  print(f'O {num1} é o maior numero.')

"""#Listas, tuplas e dicionarios"""

[1,2,3,4,5]

(1,2,3,4,5)

{'num1': 1, 'num2': 2}

"""Lista"""

lista = [5, 'Bruno', 8.9]
type(lista)

lista.append('Augusto') #Adicionar um elemento na lista

print(lista)
print(lista[1])

"""Tupla"""

tupla = (5, 'Bruno', 8.9)

type(tupla)

tupla.append('Augusto')

print(tupla)

"""Dicionario"""

dicionario = {'nome':'Bruno', 'cidade':'Porto Alegre'}

type(dicionario)

print(dicionario)

print(dicionario['nome'])

dicionario['ultimo_nome'] = 'Hoffmann'

print(dicionario)

"""#Estrutura de repetição

For
"""

#For Range
for contador in range(10):
  print(contador)

#For Range + Break
for contador in range(1000):
  print(contador)
  if contador == 2:
    break

lista = ['Teste1', 'Teste2']

#For Simples
for val in lista:
  print(val)

for i, val in enumerate(lista):
  print(i, val)

"""For com operadores compostos"""

lista2 = [2,3,4]

for val in lista2:
  val += 1
  print(val)

for val in lista2:
  val *=2
  print(val)

"""While"""

val = 1
while (val < 6):
  val *= 2
  print(val)

#while com else
val = 10
while (val < 6):
  val *= 2
else:
  print(f'Valor de val é: {val}')

